version: 2

models:
  - name: stg_addresses
    description: "Addresses Table"
    columns:
      - name: address_id
        description: UUID for each unique address on platform
        tests:
          - unique
          - not_null
      - name: address
        description: The first few lines of the address
      - name: zipcode
        description: The zipcode of the address
      - name: state
        description: state this delivery address is based in
      - name: country
        description: country this delivery address is based in

  - name: stg_users
    description: "Users Table"
    columns:
      - name: user_id
        description: UUID for each unique user on platform
        tests:
          - unique
          - not_null
      - name: first_name
        description: first name of the user
      - name: last_name
        description: last name of the user
      - name: email
        description: email address of the user
      - name: phone_number
        description: phone number of the user
      - name: created_at
        description: timestamp the user was created
      - name: updated_at
        description: timestamp the user was last updated
      - name: address_id
        description: default delivery address for the user

  - name: stg_promos
    description: "Promos Table"
    columns:
      - name: promo_id
        description: Each unique promocode on platform
        tests:
          - unique
          - not_null
      - name: discount
        description: Absolute dollar amount that is given off with the code
      - name: status
        description: Is the promo code active or disabled

  - name: stg_products
    description: "Products Table"
    columns:
      - name: product_id
        description: UUID for each unique product on platform
        tests:
          - unique
          - not_null
      - name: name
        description: Name of the product
      - name: price
        description: Price of the product
      - name: inventory
        description: Amount of the inventory we have for this product
