version: 2

sources:

  - name: greenery
    schema: public
    database: dbt

    quoting:
      database: false
      schema: false
      identifier: false

    freshness:
      warn_after: {count: 24, period: hour}
      error_after: {count: 48, period: hour}

    tables:
      - name: addresses
      - name: users
        loaded_at_field: created_at
      - name: promos
      - name: products
      - name: orders
        loaded_at_field: created_at
      - name: order_items
